### ISSUE TITLE
pyarchinit su win10

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#4]
Salve, aggiungo due problemi da risolvere per l'installazione di pyarchinit su windwos10 utilizzando qgis3.01 standalone (32bit).

1 non può importare il modulo test (in qgis standalone il modulo test di python non esiste)
2 Pyagraphviz non si riesce ad installare su win10 con python3 (32bit). Pertanto pyarchinit non viene caricato

**Comment by slarosa** [comment]
Puoi incollare il listato degli errori che riscontri?

**Comment by enzococca** [comment]
per quanto riguarda il primo problema ecco il codice di errore: (Da notare che in qgis3 standalone per windows R non c'è ...ancora)

ModuleNotFoundError: No module named 'test.test_heapq' 
Traceback (most recent call last):
  File "C:/PROGRA~2/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/enzo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-qgis3_porting\__init__.py", line 34, in classFactory
    from .pyarchinit_plugin import PyArchInitPlugin
  File "C:/PROGRA~2/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/enzo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-qgis3_porting\pyarchinit_plugin.py", line 36, in 
    from .pyarchinit_Archeozoology_mainapp import pyarchinit_Archeozoology
  File "C:/PROGRA~2/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/enzo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-qgis3_porting\pyarchinit_Archeozoology_mainapp.py", line 27, in 
    from test.test_heapq import R
  File "C:/PROGRA~2/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'test.test_heapq'

**Comment by enzococca** [comment]
per il secondo pyagraphviz  ecco il codice di errore 
 pygraphviz/graphviz_wrap.c(2954): fatal error C1083: Cannot open include file: 'graphviz/cgraph.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

**Comment by enzococca** [comment]
pygraphviz ho provato a compilarlo sia sotto python di qgis che indipendentemente ma non ci sono riuscito, mentre il modulo test l'ho baipassato semplicemente commentandolo. Io utilizzavo il modulo Pyper per far funzionare R..

**Comment by enzococca** [comment]
Suggerirei di commentare la riga 27 
**from test.test_heapq import R**
 in Archeozoologymainapp.py dato che R ancora non è implemetato in qgis3 di default

**Comment by slarosa** [comment]
Possiamo chiudere?

**Comment by enzococca** [comment]
Credo si!!

Il Gio 19 Apr 2018, 17:33 Salvatore Larosa <notifications@github.com> ha
scritto:
