### ISSUE TITLE
Scheda sito: 

### ISSUE THREAD

**Issue by pyarchinit** [serenasensini/pyarchinit_3#46]
Nella scheda sito, nella tab Tools, abilitando il toogle button "abilità il caricamento delle ricerche", dopo aver eseguito una ricerca QGIS RITORNA IL SEGUENTE MESSAGGIO:

Si è verificato un errore durante l'esecuzione del codice Python: 

UnboundLocalError: local variable 'db_file_path' referenced before assignment 
Traceback (most recent call last):
  File "C:/Users/Windows/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\pyarchinit_Site_mainapp.py", line 593, in on_pushButton_search_go_pressed
    self.pyQGIS.charge_sites_from_research(sing_layer)
  File "C:/Users/Windows/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\modules\gis\pyarchinit_pyqgis.py", line 1371, in charge_sites_from_research
    uri.setDatabase(db_file_path)
UnboundLocalError: local variable 'db_file_path' referenced before assignment

**Comment by slarosa** [comment]
Duplicates of #45 (already fixed in master)
