### ISSUE TITLE
Errore in apertura

### ISSUE THREAD

**Issue by MicGeos** [serenasensini/pyarchinit_3#54]
Impossibile caricare il plugin 'pyarchinit_3-master' a causa di un errore chiamando il metodo classFactory() 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.1/apps/qgis-dev/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/micza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\__init__.py", line 39, in classFactory
    from .pyarchinit_plugin import PyArchInitPlugin
  File "C:/PROGRA~1/QGIS3~1.1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/micza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\pyarchinit_plugin.py", line 35, in 
    from .pyarchinit_Archeozoology_mainapp import pyarchinit_Archeozoology
  File "C:/PROGRA~1/QGIS3~1.1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/micza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\pyarchinit_Archeozoology_mainapp.py", line 43, in 
    from .pyarchinit_US_mainapp import pyarchinit_US
  File "C:/PROGRA~1/QGIS3~1.1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/micza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\pyarchinit_US_mainapp.py", line 40, in 
    from .modules.utility.pyarchinit_exp_Periodosheet_pdf import generate_US_pdf
  File "C:/PROGRA~1/QGIS3~1.1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/micza/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit_3-master\modules\utility\pyarchinit_exp_Periodosheet_pdf.py", line 28, in 
    from reportlab.lib import colors
  File "C:/PROGRA~1/QGIS3~1.1/apps/qgis-dev/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.1\apps\Python36\lib\site-packages\reportlab\lib\colors.py", line 388
    raise ValueError, "Can't interpolate: x=%f is not between %f and %f!" % (x,x0,x1)
                    ^
SyntaxError: invalid syntax

Versione Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Versione di QGIS: 3.1.0-Master Master, 6fb5777cc6

**Comment by MicGeos** [comment]
Risolto: mancava il modulo reportlab all'interno di python 3.6 di QGIS
