### ISSUE TITLE
scheda reperti: TypeError: __init__() missing 1 required positional argument: 'figure' 

### ISSUE THREAD

**Issue by enzococca** [serenasensini/pyarchinit_3#6]
sistema operativo ubuntu16.04

TypeError: __init__() missing 1 required positional argument: 'figure' 
Traceback (most recent call last):
  File "/home/enzo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit_3-master/pyarchinitplugindialog.py", line 98, in runInr
    pluginGui = pyarchinit_Inventario_reperti(self.iface)
  File "/home/enzo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit_3-master/pyarchinit_Inv_Materiali_mainapp.py", line 206, in __init__
    self.setupUi(self)
  File "", line 860, in setupUi
  File "/home/enzo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit_3-master/modules/utility/mplwidget.py", line 23, in __init__
    self.canvas = MplCanvas()
  File "/home/enzo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit_3-master/modules/utility/mplwidget.py", line 15, in __init__
    FigureCanvas.__init__(self, self.fig)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() missing 1 required positional argument: 'figure'

**Comment by slarosa** [comment]
da testare...grazie
